version: '3.7'

services:
  mariadb:
    container_name: docker-mariadb
    image: mariadb:10.5.5
    init: true
    user: root
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --sql-mode=
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    ports:
      - 13306:3306
    env_file: .env
    environment:
      TZ: Asia/Seoul